/*
    Live data fetching of NSE - Option Chain - NIFTY50
*/
let
    Source = Json.Document(Web.Contents("https://nseindia.com/api/liveEquity-derivatives?index=nse50_opt", [Headers=[#"User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36", #"Accept-Encoding"="gzip, deflate", #"Accept-Language"="en-GB,en-US;q=0.9,en;q=0.8,hi;q=0.7", Referer="https://www.nseindia.com/market-data/equity-derivatives-watch", Cookie="nsit=jNyuE8j3yj_MEAH4qvj_6GV8; _ga=GA1.2.2092314534.1604238254; _gid=GA1.2.1200080433.1604238254; _gat_UA-143761337-1=1; ak_bmsc=DC1DA1DF16A87DE73D126A424882C44873F8EE3557540000ACBB9E5FF0BA0E47~plJtOJEcymhY4qVQ9j3ZMB+FDAwjkThhBmx9NIquPqHpcGuCa+Q0TElCAZhCHHnqR76iHpGZQqVjutU/SJQJXUn/Y78daBbzJ4DgE10ch8Rd4m6bkzZz2Zqa/9vSxvEv24XJ23PIOHme5MR+o9srUD9jT0FZaBMjPeZHnmirhe5TnRX9nSEEJuFLlw5Fqi4RPk2NagNst19ZeEkcrJBikn+9sQ57v12LcxVLvbgxg05ks1LfKHUb7eMHJctlKrg7OW; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTYwNDIzODI2MiwiZXhwIjoxNjA0MjQxODYyfQ.vena0DAmCjLoBg2xVTszPxcUGyh8guFZdj-1tZCgpUE; RT=""z=1&dm=nseindia.com&si=ddffbd0a-f8fa-4c72-baba-bcc8e4d93ab6&ss=kgz6188r&sl=2&tt=4om&bcn=%2F%2F684fc53c.akstat.io%2F&ld=8r3""; bm_sv=819B3E4AAE5A3C4AB6D79BE310508196~YJdXHHEC6hJvcAgedAPRJVBnOfWgIZlqGi2jpWqRZ6jAjk2EO46fL2rnngtDbkRSTXQzyZY4uQMRlZb8240XLi7MDnjpywNnXoBHueMSF8XfNEhiHDGIG8qcIzXcnitq8VNvFFJLZcPHeKW6w7CtsOJeudpGtIHNMyVg3oqCUxE="]])),
    data = Source[data],
    #"Converted to Table" = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"underlying", "identifier", "instrumentType", "instrument", "contract", "expiryDate", "optionType", "strikePrice", "lastPrice", "change", "pChange", "volume", "totalTurnover", "value", "premiumTurnOver", "underlyingValue", "openInterest", "noOfTrades"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"underlying", type text}, {"identifier", type text}, {"instrumentType", type text}, {"instrument", type text}, {"contract", type text}, {"optionType", type text}, {"expiryDate", type date}, {"strikePrice", type number}, {"lastPrice", type number}, {"change", type number}, {"pChange", type number}, {"volume", type number}, {"totalTurnover", type number}, {"value", type number}, {"premiumTurnOver", type number}, {"underlyingValue", type number}, {"openInterest", type number}, {"noOfTrades", type number}})
in
    #"Changed Type"