/*
    Live data fetching of NSE - Option Chain - Any security (?symbol=NSE_CODE)
*/
let
    Source = Json.Document(Web.Contents("https://nseindia.com/api/option-chain-equities?symbol=SBIN", [Headers=[#"User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36", #"Accept-Encoding"="gzip, deflate", #"Accept-Language"="en-GB,en-US;q=0.9,en;q=0.8,hi;q=0.7", Cookie="D4ABA0C764C211BD823CC5EB9C2EB8CB~5VIXshJdu4xId2K+NthIgVyT8DyfKFho4j8Wh0XJsxIEX9DYtGMD9G+i8h0dxB0c3mEqt4csbUvknV81AupMmIEZnVgE+AgQ4hUiCocQBVAhP2YuaBuJGkxOy4FPmhaMvP3+pXtpQinxKp/3y3VFWXKA/th2Ed2Szh30fEiBKnM="]])),
    records = Source[records],
    data = records[data],
    #"Converted to Table" = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"strikePrice", "expiryDate", "PE", "CE"}, {"strikePrice", "expiryDate", "PE", "CE"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"expiryDate", type date}, {"strikePrice", type number}}),
    #"Expanded PE" = Table.ExpandRecordColumn(#"Changed Type", "PE", {"strikePrice", "expiryDate", "underlying", "identifier", "openInterest", "changeinOpenInterest", "pchangeinOpenInterest", "totalTradedVolume", "impliedVolatility", "lastPrice", "change", "pChange", "totalBuyQuantity", "totalSellQuantity", "bidQty", "bidprice", "askQty", "askPrice", "underlyingValue"}, {"PE.strikePrice", "PE.expiryDate", "PE.underlying", "PE.identifier", "PE.openInterest", "PE.changeinOpenInterest", "PE.pchangeinOpenInterest", "PE.totalTradedVolume", "PE.impliedVolatility", "PE.lastPrice", "PE.change", "PE.pChange", "PE.totalBuyQuantity", "PE.totalSellQuantity", "PE.bidQty", "PE.bidprice", "PE.askQty", "PE.askPrice", "PE.underlyingValue"}),
    #"Expanded CE" = Table.ExpandRecordColumn(#"Expanded PE", "CE", {"strikePrice", "expiryDate", "underlying", "identifier", "openInterest", "changeinOpenInterest", "pchangeinOpenInterest", "totalTradedVolume", "impliedVolatility", "lastPrice", "change", "pChange", "totalBuyQuantity", "totalSellQuantity", "bidQty", "bidprice", "askQty", "askPrice", "underlyingValue"}, {"CE.strikePrice", "CE.expiryDate", "CE.underlying", "CE.identifier", "CE.openInterest", "CE.changeinOpenInterest", "CE.pchangeinOpenInterest", "CE.totalTradedVolume", "CE.impliedVolatility", "CE.lastPrice", "CE.change", "CE.pChange", "CE.totalBuyQuantity", "CE.totalSellQuantity", "CE.bidQty", "CE.bidprice", "CE.askQty", "CE.askPrice", "CE.underlyingValue"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded CE",{"PE.strikePrice", "PE.expiryDate", "CE.strikePrice", "CE.expiryDate", "CE.underlying"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"PE.openInterest", type number}, {"PE.changeinOpenInterest", type number}, {"PE.pchangeinOpenInterest", type number}, {"PE.totalTradedVolume", type number}, {"PE.impliedVolatility", type number}, {"PE.lastPrice", type number}, {"PE.change", type number}, {"PE.pChange", type number}, {"PE.totalBuyQuantity", type number}, {"PE.totalSellQuantity", type number}, {"PE.bidQty", type number}, {"PE.bidprice", type number}, {"PE.askQty", type number}, {"PE.askPrice", type number}, {"PE.underlyingValue", type number}, {"CE.openInterest", type number}, {"CE.changeinOpenInterest", type number}, {"CE.pchangeinOpenInterest", type number}, {"CE.totalTradedVolume", type number}, {"CE.impliedVolatility", type number}, {"CE.lastPrice", type number}, {"CE.change", type number}, {"CE.pChange", type number}, {"CE.totalBuyQuantity", type number}, {"CE.totalSellQuantity", type number}, {"CE.bidQty", type number}, {"CE.bidprice", type number}, {"CE.askQty", type number}, {"CE.askPrice", type number}, {"CE.underlyingValue", type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"PE.underlying", "symbol"}})
in
    #"Renamed Columns"