/*
    Live data fetching of NSE - Option Chain - Any security (?symbol=NSE_CODE)
*/
let
    Source = Json.Document(Web.Contents("https://nseindia.com/api/option-chain-equities?symbol=SBIN", [Headers=[#"User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36", #"Accept-Encoding"="gzip, deflate", #"Accept-Language"="en-GB,en-US;q=0.9,en;q=0.8,hi;q=0.7", Referer="https://www.nseindia.com/market-data/equity-derivatives-watch", Cookie="nsit=jNyuE8j3yj_MEAH4qvj_6GV8; _ga=GA1.2.2092314534.1604238254; _gid=GA1.2.1200080433.1604238254; _gat_UA-143761337-1=1; ak_bmsc=DC1DA1DF16A87DE73D126A424882C44873F8EE3557540000ACBB9E5FF0BA0E47~plJtOJEcymhY4qVQ9j3ZMB+FDAwjkThhBmx9NIquPqHpcGuCa+Q0TElCAZhCHHnqR76iHpGZQqVjutU/SJQJXUn/Y78daBbzJ4DgE10ch8Rd4m6bkzZz2Zqa/9vSxvEv24XJ23PIOHme5MR+o9srUD9jT0FZaBMjPeZHnmirhe5TnRX9nSEEJuFLlw5Fqi4RPk2NagNst19ZeEkcrJBikn+9sQ57v12LcxVLvbgxg05ks1LfKHUb7eMHJctlKrg7OW; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTYwNDIzODI2MiwiZXhwIjoxNjA0MjQxODYyfQ.vena0DAmCjLoBg2xVTszPxcUGyh8guFZdj-1tZCgpUE; RT=""z=1&dm=nseindia.com&si=ddffbd0a-f8fa-4c72-baba-bcc8e4d93ab6&ss=kgz6188r&sl=2&tt=4om&bcn=%2F%2F684fc53c.akstat.io%2F&ld=8r3""; bm_sv=819B3E4AAE5A3C4AB6D79BE310508196~YJdXHHEC6hJvcAgedAPRJVBnOfWgIZlqGi2jpWqRZ6jAjk2EO46fL2rnngtDbkRSTXQzyZY4uQMRlZb8240XLi7MDnjpywNnXoBHueMSF8XfNEhiHDGIG8qcIzXcnitq8VNvFFJLZcPHeKW6w7CtsOJeudpGtIHNMyVg3oqCUxE="]])),
    records = Source[records],
    data = records[data],
    #"Converted to Table" = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"strikePrice", "expiryDate", "PE", "CE"}, {"strikePrice", "expiryDate", "PE", "CE"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"expiryDate", type date}, {"strikePrice", type number}}),
    #"Expanded PE" = Table.ExpandRecordColumn(#"Changed Type", "PE", {"strikePrice", "expiryDate", "underlying", "identifier", "openInterest", "changeinOpenInterest", "pchangeinOpenInterest", "totalTradedVolume", "impliedVolatility", "lastPrice", "change", "pChange", "totalBuyQuantity", "totalSellQuantity", "bidQty", "bidprice", "askQty", "askPrice", "underlyingValue"}, {"PE.strikePrice", "PE.expiryDate", "PE.underlying", "PE.identifier", "PE.openInterest", "PE.changeinOpenInterest", "PE.pchangeinOpenInterest", "PE.totalTradedVolume", "PE.impliedVolatility", "PE.lastPrice", "PE.change", "PE.pChange", "PE.totalBuyQuantity", "PE.totalSellQuantity", "PE.bidQty", "PE.bidprice", "PE.askQty", "PE.askPrice", "PE.underlyingValue"}),
    #"Expanded CE" = Table.ExpandRecordColumn(#"Expanded PE", "CE", {"strikePrice", "expiryDate", "underlying", "identifier", "openInterest", "changeinOpenInterest", "pchangeinOpenInterest", "totalTradedVolume", "impliedVolatility", "lastPrice", "change", "pChange", "totalBuyQuantity", "totalSellQuantity", "bidQty", "bidprice", "askQty", "askPrice", "underlyingValue"}, {"CE.strikePrice", "CE.expiryDate", "CE.underlying", "CE.identifier", "CE.openInterest", "CE.changeinOpenInterest", "CE.pchangeinOpenInterest", "CE.totalTradedVolume", "CE.impliedVolatility", "CE.lastPrice", "CE.change", "CE.pChange", "CE.totalBuyQuantity", "CE.totalSellQuantity", "CE.bidQty", "CE.bidprice", "CE.askQty", "CE.askPrice", "CE.underlyingValue"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded CE",{"PE.strikePrice", "PE.expiryDate", "CE.strikePrice", "CE.expiryDate", "CE.underlying"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"PE.openInterest", type number}, {"PE.changeinOpenInterest", type number}, {"PE.pchangeinOpenInterest", type number}, {"PE.totalTradedVolume", type number}, {"PE.impliedVolatility", type number}, {"PE.lastPrice", type number}, {"PE.change", type number}, {"PE.pChange", type number}, {"PE.totalBuyQuantity", type number}, {"PE.totalSellQuantity", type number}, {"PE.bidQty", type number}, {"PE.bidprice", type number}, {"PE.askQty", type number}, {"PE.askPrice", type number}, {"PE.underlyingValue", type number}, {"CE.openInterest", type number}, {"CE.changeinOpenInterest", type number}, {"CE.pchangeinOpenInterest", type number}, {"CE.totalTradedVolume", type number}, {"CE.impliedVolatility", type number}, {"CE.lastPrice", type number}, {"CE.change", type number}, {"CE.pChange", type number}, {"CE.totalBuyQuantity", type number}, {"CE.totalSellQuantity", type number}, {"CE.bidQty", type number}, {"CE.bidprice", type number}, {"CE.askQty", type number}, {"CE.askPrice", type number}, {"CE.underlyingValue", type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"PE.underlying", "symbol"}})
in
    #"Renamed Columns"